services:


  # --- kafka ---

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
#    volumes:
#      - "zookeeper-data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend-kafka

  broker-1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
#    volumes:
#      - "broker-1-data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker-1:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_MESSAGE_MAX_BYTES=15728641          #  max message size 15 Mb  +  1 Mb for message metadata
      - KAFKA_REPLICA_FETCH_MAX_BYTES=15728641    #  max message size 15 Mb  +  1 Mb for message metadata
    depends_on:
      - zookeeper
    networks:
      - backend-kafka

  broker-2:
    image: bitnami/kafka:latest
    ports:
      - "9094:9094"
      - "9095:9095"
#    volumes:
#      - "broker-2-data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9094,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker-2:9094,EXTERNAL://localhost:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_MESSAGE_MAX_BYTES=15728641          #  max message size 15 Mb  +  1 Mb for message metadata
      - KAFKA_REPLICA_FETCH_MAX_BYTES=15728641    #  max message size 15 Mb  +  1 Mb for message metadata
    depends_on:
      - zookeeper
    networks:
      - backend-kafka


  # --- database-1 ---

  postgresql-1:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crypto_messenger
      POSTGRES_USER: eflerrr
      POSTGRES_PASSWORD: heyheyhey
    networks:
      - backend-1


  # --- migrations-1 ---

  liquibase-migrations-1:
    image: liquibase:alpine
    depends_on:
      - postgresql-1
    command:
      - --search-path=/liquibase/changelog
      - --changeLogFile=changelog-master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql-1:5432/crypto_messenger
      - --username=eflerrr
      - --password=heyheyhey
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend-1


  # --- database-2 ---

  postgresql-2:
    image: postgres:latest
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: crypto_messenger
      POSTGRES_USER: eflerrr
      POSTGRES_PASSWORD: hahaha
    networks:
      - backend-2


  # --- migrations-2 ---

  liquibase-migrations-2:
    image: liquibase:alpine
    depends_on:
      - postgresql-2
    command:
      - --search-path=/liquibase/changelog
      - --changeLogFile=changelog-master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql-2:5432/crypto_messenger
      - --username=eflerrr
      - --password=hahaha
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend-2


networks:
  backend-kafka: { }
  backend-1: { }
  backend-2: { }



#volumes:
#  zookeeper-data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./docker-volumes/zookeeper-data
#  broker-1-data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./docker-volumes/broker-1-data
#  broker-2-data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./docker-volumes/broker-2-data
