services:


  # --- kafka ---

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
#    volumes:
#      - "zookeeper-data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend

  broker-1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
#    volumes:
#      - "broker-1-data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker-1:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_MESSAGE_MAX_BYTES=10485761          #  max message size 10 Mb  +  1 Mb for message metadata
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10485761    #  max message size 10 Mb  +  1 Mb for message metadata
    depends_on:
      - zookeeper
    networks:
      - backend

  broker-2:
    image: bitnami/kafka:latest
    ports:
      - "9094:9094"
      - "9095:9095"
#    volumes:
#      - "broker-2-data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9094,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker-2:9094,EXTERNAL://localhost:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_MESSAGE_MAX_BYTES=10485761          #  max message size 10 Mb  +  1 Mb for message metadata
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10485761    #  max message size 10 Mb  +  1 Mb for message metadata
    depends_on:
      - zookeeper
    networks:
      - backend


#volumes:
#  zookeeper-data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./docker-volumes/zookeeper-data
#  broker-1-data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./docker-volumes/broker-1-data
#  broker-2-data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./docker-volumes/broker-2-data


networks:
  backend: { }
