app-configs:
  host: ${APP_HOST:localhost}
  port: ${APP_PORT:8080}
  clients:
    protocol: ${CLIENTS_PROTOCOL:HTTP}
    root-endpoint: ${CLIENTS_ROOT_ENDPOINT:/client-chat}
    public-key-endpoint: ${CLIENTS_PUBLIC_KEY_ENDPOINT:/public-key}
    notify-exit-endpoint: ${CLIENTS_NOTIFY_EXIT_ENDPOINT:/client-exit}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    topics-replication-factor: ${KAFKA_TOPICS_REPLICATION_FACTOR:2}
    topics-postfix: ${KAFKA_TOPICS_POSTFIX:-chat}
  diffie-hellman:
    bit-length: ${DIFFIE_HELLMAN_BIT_LENGTH:100}

spring:
  application:
    name: ${APP_NAME:server}
  kafka:
    bootstrap-servers: ${app-configs.kafka.bootstrap-servers}
    admin:
      client-id: ${KAFKA_ADMIN_CLIENT_ID:server-admin}

springdoc:
  swagger-ui:
    path: /endpoints

server:
  port: ${app-configs.port}
