app-configs:
  host: ${APP_HOST:localhost}
  port: ${APP_PORT:8082}
  gateway-endpoint: ${GATEWAY_ENDPOINT:/hello}
  server:
    protocol: ${SERVER_PROTOCOL:HTTP}
    host: ${SERVER_HOST:localhost}
    port: ${SERVER_PORT:8080}
    chat:
      endpoint: ${SERVER_CHAT_ENDPOINT:/chat}
    chat-list:
      endpoint: ${SERVER_CHAT_LIST_ENDPOINT:/chat/list}
      update-interval: ${SERVER_CHAT_LIST_UPDATE_INTERVAL:3000ms}
  file-upload:
    in-memory: ${FILE_UPLOAD_IN_MEMORY:true}
    max-file-size: ${FILE_UPLOAD_MAX_FILE_SIZE:15728640}  # 15 Mb
  encryption:
    private-key-bit-length: ${ENCRYPTION_PRIVATE_KEY_BIT_LENGTH:1024}
  kafka:
    max-request-size: ${KAFKA_MAX_REQUEST_SIZE:15728641}  # 15 Mb (file-max-size)  +  1 mb for message metadata  [producer prop]
    fetch-max-bytes: ${KAFKA_FETCH_MAX_BYTES:15728641}  # 15 Mb (file-max-size)  +  1 mb for message metadata  [consumer prop]
  database:
    messages:
      save-encrypted: ${DB_MESSAGES_SAVE_ENCRYPTED:true}

spring:
  application:
    name: ${APP_NAME:client}
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: ${app-configs.file-upload.max-file-size}
  spring:
    json:
      trusted:
        packages: "*"
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:crypto_messenger}
    username: ${DB_USERNAME:eflerrr}
    password: ${DB_PASSWORD:heyheyhey}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

springdoc:
  swagger-ui:
    path: /endpoints

server:
  port: ${app-configs.port}

vaadin:
  frontend:
    hotdeploy: true
  url-mapping: /*
  excludeUrls: "/swagger-ui/**, /v3/api-docs/**, ${springdoc.swagger-ui.path}, /client-chat/**"
