app-configs:
  server-url: http://localhost:8080
  chat-list:
    update-interval: 3000ms
    endpoint: /chat/list
  chat-endpoint: /chat
  server:
    host: localhost
    port: ${APP_PORT:8082}
    gateway-url: /hello
  file-upload:
    in-memory: true
    file-max-size: 15728640  # 15 Mb
  encryption:
    private-key-bit-length: 1024
  kafka:
    max-request-size: 15728641  # 15 Mb (file-max-size)  +  1 mb for message metadata  [producer prop]
    fetch-max-bytes: 15728641  # 15 Mb (file-max-size)  +  1 mb for message metadata  [consumer prop]
  database:
    messages:
      save-encrypted: true

spring:
  application:
    name: client
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: ${app-configs.file-upload.file-max-size}
  spring:
    json:
      trusted:
        packages: "*"
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/crypto_messenger
    username: ${DB_USERNAME:eflerrr}
    password: ${DB_PASSWORD:heyheyhey}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

springdoc:
  swagger-ui:
    path: /endpoints

server:
  port: ${app-configs.server.port}

vaadin:
  frontend:
    hotdeploy: true
  url-mapping: /*
  excludeUrls: "/swagger-ui/**, /v3/api-docs/**, ${springdoc.swagger-ui.path}, /client-chat/**"
