app-configs:
  server-url: http://localhost:8080
  chat-list:
    update-interval: 3000ms
    endpoint: /chat/list
  chat-endpoint: /chat
  server:
    host: localhost
    port: 8082
    gateway-url: /hello
  file-upload:
    in-memory: true
    file-max-size: 10485760  # 10 Mb

spring:
  application:
    name: client
  servlet:
    multipart:
      max-file-size: ${app-configs.file-upload.file-max-size}

springdoc:
  swagger-ui:
    path: /endpoints

server:
  port: ${app-configs.server.port}

vaadin:
  frontend:
    hotdeploy: true
