app-configs:
  server-url: http://localhost:8080
  chat-list:
    update-interval: 3000ms
    endpoint: /chat/list
  chat-endpoint: /chat
  server:
    host: localhost
    port: 8081

spring:
  application:
    name: client

springdoc:
  swagger-ui:
    path: /endpoints

server:
  port: ${app-configs.server.port}
