app-configs:
  server-url: http://localhost:8080
  chat-list:
    update-interval: 3000ms
    endpoint: /chat/list

spring:
  application:
    name: client

springdoc:
  swagger-ui:
    path: /endpoints

server:
  port: 8081
